<main class="main-page">
    <div class="main-area card" style="padding: 1em;">
        <h2 class="code-line" data-line-start=0 data-line-end=1 ><a id="1_Leistungsbeschreibung_und_Bewerbung_der_Angebote_0"></a>1 Leistungsbeschreibung und Bewerbung der Angebote</h2>
        <ol>
            <li class="has-line-data" data-line-start="1" data-line-end="2">Platypurse stellt mit den Platypurse-Diensten einen Online-Service zur Verfügung, über den der Nutzer als Inserent aus Texten und Bildern bestehende Angebote und Gesuche (im Folgenden „Angebote“) erstellen und veröffentlichen sowie als Interessent veröffentlichte Angebote anderer Nutzer einsehen kann. Darüber hinaus ermöglichen die Platypurse-Dienste auch den Austausch elektronischer Nachrichten zwischen Inserenten und Interessenten. Soweit dies zur Konvertierung in für die Platypurse-Dienste taugliche Dateiformate erforderlich ist, wird Platypurse die Angebote des Nutzers in Formate für die Nutzung in mobilen Anwendungen und Webseiten konvertieren.</li>
            <li class="has-line-data" data-line-start="2" data-line-end="3">Die Platypurse-Dienste dienen dem Veröffentlichen von Angebote und dem Zusammenführen von Anbietern und Interessenten der eingestellten Waren. Platypurse ist selbst nicht Anbieter der jeweils mit den Angebote beworbenen Produkte.</li>
            <li class="has-line-data" data-line-start="3" data-line-end="4">Im Rahmen der Angebotedarstellung und auf der Übersichtsseite eines Nutzers zeigt Platypurse zusätzliche Angaben zum Nutzer und dessen Aktivitäten in den Platypurse-Diensten an (dies kann z.B. die Bewertung eines Nutzers durch andere Nutzer sein) Platypurse kann den Nutzer zudem anhand bestimmter Kriterien kennzeichnen.</li>
            <li class="has-line-data" data-line-start="4" data-line-end="5">Platypurse ermöglicht es Nutzern, sich basierend auf einer konkreten Interaktion miteinander gegenseitig und öffentlich zugänglich zu bewerten. Die Nutzung des Bewertungssystems richtet sich nach dem Grundsatz zur Bewertungsfunktion von Platypurse.</li>
            <li class="has-line-data" data-line-start="5" data-line-end="6">Platypurse ermöglicht es Nutzern, Angebote zu folgen.</li>
            <li class="has-line-data" data-line-start="6" data-line-end="8">Platypurse ermöglicht es den Nutzern, die Suchergebnisse anhand verschiedener Kriterien zu sortieren (bspw. Alter, Gewicht).</li>
        </ol>
        <h2 class="code-line" data-line-start=8 data-line-end=9 ><a id="2_Registrierung_Nutzerkonto_8"></a>2 Registrierung, Nutzerkonto</h2>
        <ol>
            <li class="has-line-data" data-line-start="9" data-line-end="10">Für die vollständige Nutzung der Platypurse-Dienste, insbesondere für das Einstellen von Angebote, das Angebote bestimmter Kontaktdaten von Inserenten und den Austausch elektronischer Nachrichten mit anderen Nutzern, ist eine Registrierung des Nutzers bei Platypurse erforderlich.</li>
            <li class="has-line-data" data-line-start="10" data-line-end="11">Der Nutzer ist verpflichtet, die bei der Registrierung von Platypurse erhobenen Daten wahrheitsgemäß und vollständig anzugeben. Bei einer Änderung der Daten nach erfolgter Registrierung ist der Nutzer verpflichtet, die Daten unverzüglich im passwortgeschützten Nutzerbereich der Platypurse-Dienste selbst zu aktualisieren.</li>
            <li class="has-line-data" data-line-start="11" data-line-end="12">Mit dem Absenden des Registrierungsformulars gibt der Nutzer ein Angebot auf den Abschluss einer Nutzungsvereinbarung mit Platypurse ab, mit dem er die Geltung der Nutzungsbedingungen akzeptiert sowie die Kenntnisnahme der Datenschutzerklärung erklärt. Akzeptiert Platypurse die Registrierung, erhält der Nutzer eine Bestätigungs-E-Mail mit einem personalisierten Link. Mit Zugang der Bestätigungs-E-Mail kommt zwischen Platypurse und dem Nutzer ein Vertrag über die Nutzung der Platypurse-Dienste (im Folgenden „Nutzungsvertrag“) zustande. Um die Registrierung abzuschließen, muss der Nutzer den mit der Bestätigungs-E-Mail mitgeteilten Link aufrufen und so seine E-Mail-Adresse verifizieren. Ein Anspruch auf Abschluss eines Nutzungsvertrages besteht nicht.</li>
            <li class="has-line-data" data-line-start="12" data-line-end="13">Mit erfolgreicher Registrierung wird für den Nutzer ein Nutzerkonto angelegt, auf das er mit Hilfe seiner E-Mail-Adresse und seines bei der Registrierung gewählten Passwortes zugreifen kann. Das Passwort kann vom Nutzer jederzeit über den passwortgeschützten Nutzerbereich geändert werden. Es ist vom Nutzer geheim zu halten und vor dem Zugriff durch unbefugte Dritte geschützt aufzubewahren. Stellt der Nutzer fest oder hegt er den Verdacht, dass seine Zugangsdaten von einem Dritten unbefugt genutzt werden, hat er dies Platypurse unverzüglich mitzuteilen und sein Passwort unverzüglich zu ändern.</li>
            <li class="has-line-data" data-line-start="13" data-line-end="14">Der Nutzer erhält auf seiner Nutzerprofilseite eine Übersicht der von ihm veröffentlichten Angebote. Zudem kann er Änderungen an seinen Einstellungen und Daten vornehmen.</li>
            <li class="has-line-data" data-line-start="14" data-line-end="16">Im Rahmen der Platypurse-Dienste hat Platypurse Zugang zu verschiedenen Informationen über Nutzer, einschließlich personenbezogener Daten. Hierzu gehören insbesondere solche Informationen, die Nutzer im Rahmen der Platypurse-Dienste an Platypurse übermitteln (z.B. Kontakt- oder Angeboteinformationen) sowie solche, die bei der Erbringung und Abwicklung der Platypurse-Dienste generiert werden (z.B. Bewertungen, Aktivitätsindikatoren oder Kommunikation). Nutzer erhalten über den Platypurse-Dienst Informationen, die für die Erbringung des Platypurse-Dienstes erforderlich sind (insbesondere die Nachrichten und Kontaktinformationen eines interessierten Käufers).</li>
        </ol>
        <p class="has-line-data" data-line-start="16" data-line-end="17">Über die Verarbeitung personenbezogener Daten durch Platypurse einschließlich der Übermittlung an Dritte und den Rechten des Nutzers als Betroffener informiert Platypurse in der <a href="./dataPrivacy">Datenschutzerklärung</a>.</p>
        <h2 class="code-line" data-line-start=18 data-line-end=19 ><a id="3_Abschluss_von_Angebote_und_ServicePaketvertrgen_18"></a>3 Abschluss von Angebote- und Service-Paketverträgen</h2>
        <ol>
            <li class="has-line-data" data-line-start="19" data-line-end="20">Hat sich der Nutzer erfolgreich bei Platypurse registriert, hat er die Möglichkeit, über die Platypurse-Dienste kostenlos eigene Angebote zu erstellen und in den Platypurse-Diensten zu veröffentlichen.</li>
            <li class="has-line-data" data-line-start="20" data-line-end="22">Die Angebotedaten werden jeweils elektronisch gespeichert. Der Nutzer kann seine Angebote im passwortgeschützten Nutzerbereich der Platypurse-Dienste verwalten, insbesondere dort auch von der öffentlichen Suche zu verstecken.</li>
        </ol>
        <h2 class="code-line" data-line-start=22 data-line-end=23 ><a id="4_Inhaltliche_Anforderungen_an_eingestellte_Angebote_22"></a>4 Inhaltliche Anforderungen an eingestellte Angebote</h2>
        <ol>
            <li class="has-line-data" data-line-start="23" data-line-end="24">Der Nutzer ist verpflichtet jedes Angebot wahrheitsgemäß und unter Angabe aller relevanten Merkmale und Eigenschaften mit Worten und möglichst auch durch aussagekräftige Bilder zu beschreiben. Des weiteren ist der Nutzer verpflichtet, alle Eingaben sorgfältig zu prüfen und nur zutreffende Vorschläge für seine Anzeige zu übernehmen.</li>
            <li class="has-line-data" data-line-start="24" data-line-end="28">
                Das Einstellen von Angebote, Texten, Bildern oder sonstigen Inhalten, die gegen gesetzliche Bestimmungen, diese Nutzungsbedingungen, Rechte Dritter oder gegen die guten Sitten verstoßen, ist untersagt. Insbesondere ist es verboten, Inhalte einzustellen,
                <ul>
                    <li class="has-line-data" data-line-start="25" data-line-end="26">die gegen urheber-, marken- und wettbewerbsrechtliche Vorschriften oder gegen gesetzliche Bestimmungen zum Jugendschutz verstoßen,</li>
                    <li class="has-line-data" data-line-start="26" data-line-end="28">die unwahre Angaben enthalten oder die sonst irreführend sind.</li>
                </ul>
            </li>
        </ol>
        <h2 class="code-line" data-line-start=28 data-line-end=29 ><a id="5_Besondere_Pflichten_des_Nutzers_28"></a>5 Besondere Pflichten des Nutzers</h2>
        <ol>
            <li class="has-line-data" data-line-start="29" data-line-end="38">
                Der Nutzer ist verpflichtet, alle Handlungen zu unterlassen, die den sicheren Betrieb der Platypurse-Dienste gefährden oder andere Nutzer belästigen könnten oder die sonst über eine bestimmungsgemäße Nutzung der Platypurse-Dienste hinausgehen. Er ist insbesondere verpflichtet, es zu unterlassen,
                <ul>
                    <li class="has-line-data" data-line-start="30" data-line-end="31">E-Mail-Werbung, SMS-Werbung, Kettenbriefe oder andere belästigende Inhalte zu versenden,</li>
                    <li class="has-line-data" data-line-start="31" data-line-end="32">Viren oder andere Technologien zu versenden, die die Platypurse-Dienste oder die Interessen bzw. das Eigentum anderer Nutzer schädigen könnten,</li>
                    <li class="has-line-data" data-line-start="32" data-line-end="33">die Infrastruktur der Platypurse-Dienste einer übermäßigen Belastung auszusetzen oder auf andere Weise das Funktionieren der Platypurse-Dienste zu stören oder zu gefährden,</li>
                    <li class="has-line-data" data-line-start="33" data-line-end="34">Inhalte von Platypurse ohne vorherige Einwilligung von Platypurse zu vervielfältigen, öffentlich zugänglich zu machen, zu verbreiten, zu bearbeiten oder sonst in einer Art und Weise zu nutzen, die über die bestimmungsgemäße Nutzung der Platypurse-Dienste hinausgeht.</li>
                    <li class="has-line-data" data-line-start="34" data-line-end="35">die Angebote oder sonstigen Inhalte Dritter ohne deren vorherige Einwilligung zu vervielfältigen, öffentlich zugänglich zu machen, zu verbreiten, zu bearbeiten oder sonst in einer Art und Weise zu nutzen, die über die bestimmungsgemäße Nutzung der Platypurse-Dienste hinausgeht.</li>
                    <li class="has-line-data" data-line-start="35" data-line-end="36">ohne die ausdrückliche schriftliche Zustimmung von Platypurse Crawler, Spider, Scraper oder andere automatisierte Mechanismen zu nutzen, um auf die Platypurse-Dienste zuzugreifen und Inhalte zu sammeln,</li>
                    <li class="has-line-data" data-line-start="36" data-line-end="37">Informationen, insbesondere E-Mail-Adressen oder Rufnummern, über andere Nutzer ohne die vorherige Einwilligung der Nutzer zu sammeln bzw. zu verwenden,</li>
                    <li class="has-line-data" data-line-start="37" data-line-end="38">Maßnahmen zu umgehen, die dazu dienen, den Zugriff auf die Platypurse-Dienste zu verhindern oder einzuschränken.</li>
                </ul>
            </li>
            <li class="has-line-data" data-line-start="38" data-line-end="40">Der Nutzer ist verpflichtet, alle innerhalb der Platypurse-Dienste gespeicherten Daten und Informationen, die er zu Zwecken der Beweissicherung, Buchführung oder zu anderen Zwecken aktuell oder künftig benötigt oder benötigen könnte, auf einem eigenen Speichermedium zu sichern und zu archivieren.</li>
        </ol>
        <h2 class="code-line" data-line-start=40 data-line-end=41 ><a id="6_Lschen_von_Angebote_Sperrung_von_Nutzern_sonstige_Manahmen_40"></a>6 Löschen von Angebote, Sperrung von Nutzern, sonstige Maßnahmen</h2>
        <ol>
            <li class="has-line-data" data-line-start="41" data-line-end="42">Platypurse ist berechtigt, in die Platypurse-Dienste eingestellte Angebote oder sonstige Inhalte des Nutzers ganz oder teilweise zu löschen oder die Veröffentlichung von Angebote oder sonstigen Inhalten des Nutzers zu verzögern oder nicht vorzunehmen, wenn konkrete Anhaltspunkte dafür vorliegen, dass die Anzeige oder der Inhalt gegen diese Nutzungsbedingungen oder gegen gesetzlichen Vorgaben verstößt, oder dass der Nutzer sonst schuldhaft vertragliche Pflichten verletzt hat. Platypurse kann den Nutzer in einem solchen Fall außerdem verwarnen und/oder vorläufig oder dauerhaft von der Nutzung der Platypurse-Dienste ausschließen. Bei einer vorläufigen oder dauerhaften Sperrung wird Platypurse den Nutzer über diesen Umstand 30 Tage vor dem Wirksamwerden der Sperrung informieren und diesen auf einem dauerhaften Datenträger (z.B. E-Mail) begründen, sofern dem keine zwingenden Gründe entgegenstehen. Die vorgenannte Frist gilt nicht, sofern die Kündigung oder dauerhafte Sperrung aufgrund zwingender gesetzlicher Bestimmungen oder behördlicher Anordnung erfolgt oder Platypurse nachweisen kann, dass der Nutzer wiederholt gegen diese Nutzungsbedingungen verstoßen hat, was zur Kündigung bzw. dauerhaften Sperrung geführt hat.</li>
            <li class="has-line-data" data-line-start="42" data-line-end="43">Platypurse behält sich außerdem vor, Angebote nicht zu veröffentlichen bzw. aus den Platypurse-Diensten zu entfernen, bei denen Anhaltspunkte dafür bestehen, dass das inserierte Produkt nicht frei verkäuflich ist oder sonst in rechtswidriger Weise angeboten wird, oder wenn Anhaltspunkte dafür vorliegen, dass die Anzeige zu missbräuchlichen Zwecken geschaltet werden soll oder wurde. Platypurse behält sich außerdem vor, bestimmte Produkte von einer Inserierung auszuschließen und entsprechende Angebote zu entfernen, wenn diese Produkte typischerweise zu missbräuchlichen Zwecken inseriert werden.</li>
            <li class="has-line-data" data-line-start="43" data-line-end="44">Wurde ein Nutzer durch Platypurse von der Nutzung der Platypurse-Dienste ausgeschlossen oder wurde der Nutzungsvertrag mit dem Nutzer beendet, darf der Nutzer die Platypurse-Dienste auch mit anderen Nutzerkonten, einschließlich solcher Nutzerkonten, die für Dritte angelegt wurden, nicht mehr nutzen und sich nicht erneut für eine Registrierung bei den Platypurse-Diensten anmelden.</li>
            <li class="has-line-data" data-line-start="44" data-line-end="45">Platypurse ist berechtigt, die Zurverfügungstellung der Platypurse-Dienste ganz oder teilweise einzuschränken oder zu beenden sowie die Veröffentlichung von Angebote oder sonstigen Inhalten von Nutzern zu verzögern, wenn dies im Hinblick auf Kapazitätsbeschränkungen, die Sicherheit oder Integrität der Server oder zur Durchführung technischer Maßnahmen erforderlich ist, oder dies der ordnungsgemäßen oder verbesserten Erbringung der Leistungen dient (Wartungsarbeiten).</li>
            <li class="has-line-data" data-line-start="45" data-line-end="47">Ergreift Platypurse eine der Maßnahmen gemäß diesem § 6, insbesondere bei einer Einschränkung, Sperrung oder Kündigung nach § 10 Nr. 2, haben Nutzer die Möglichkeit, den einer solchen Maßnahmen zugrunde liegenden Sachverhalt im Rahmen des internen Beschwerdemanagementverfahrens des Kundenservices von Platypurse (vgl. § 1 Nr. 7 dieser Nutzungsbedingungen) zu klären.</li>
        </ol>
        <h2 class="code-line" data-line-start=47 data-line-end=48 ><a id="7_Haftung_von_Platypurse_47"></a>7 Haftung von Platypurse</h2>
        <ol>
            <li class="has-line-data" data-line-start="48" data-line-end="49">Die in den Platypurse-Diensten veröffentlichten Angebote und sonstigen Inhalte von Nutzern geben nicht die Meinung von Platypurse wieder und werden von Platypurse nicht auf ihre Rechtmäßigkeit, Richtigkeit und Vollständigkeit überprüft. Platypurse übernimmt keine Gewähr für die Richtigkeit und Vollständigkeit der in den Angebote enthaltenen Angaben und auch keine Gewähr für die Qualität, Sicherheit oder Rechtmäßigkeit der von Nutzern angebotenen Waren oder Dienstleistungen.</li>
            <li class="has-line-data" data-line-start="49" data-line-end="50">Platypurse haftet nach den gesetzlichen Vorschriften für Vorsatz und grobe Fahrlässigkeit von Platypurse, ihren gesetzlichen Vertretern, leitenden Angestellten oder sonstigen Erfüllungsgehilfen. Gleiches gilt bei der Übernahme von Garantien oder einer sonstigen Übernahme einer verschuldensunabhängigen Haftung sowie bei Ansprüchen nach dem Produkthaftungsgesetz oder bei einer schuldhaften Verletzung des Lebens, des Körpers oder der Gesundheit. Platypurse haftet zudem dem Grunde nach für durch Platypurse, ihre Vertreter, leitende Angestellten und sonstige Erfüllungsgehilfen verursachte einfach fahrlässige Verletzungen wesentlicher Vertragspflichten, also solcher Pflichten, auf deren Erfüllung der Nutzer zur ordnungsgemäßen Durchführung des Vertrages regelmäßig vertraut und vertrauen darf, in diesem Fall aber der Höhe nach begrenzt auf den typischerweise entstehenden, vorhersehbaren Schaden. Eine weitergehende Haftung von Platypurse ist ausgeschlossen.</li>
            <li class="has-line-data" data-line-start="50" data-line-end="52">oweit die Haftung von Platypurse ausgeschlossen oder beschränkt ist, gilt dies auch zugunsten der persönlichen Haftung ihrer gesetzlichen Vertreter, leitenden Angestellten und sonstigen Erfüllungsgehilfen.</li>
        </ol>
        <h2 class="code-line" data-line-start=52 data-line-end=53 ><a id="8_Haftung_des_Nutzers_52"></a>8 Haftung des Nutzers</h2>
        <ol>
            <li class="has-line-data" data-line-start="53" data-line-end="54">Der Nutzer stellt Platypurse von sämtlichen Ansprüchen frei, die andere Nutzer oder sonstige Dritte wegen einer Verletzung ihrer Rechte durch von dem Nutzer in die Platypurse-Dienste eingestellten Angebote und sonstigen Inhalten oder wegen dessen sonstiger Nutzung der Platypurse-Dienste gegenüber Platypurse geltend machen. Der Nutzer übernimmt hierbei die Kosten der notwendigen Rechtsverteidigung von Platypurse einschließlich sämtlicher Gerichts- und Anwaltskosten in gesetzlicher Höhe. Der Anspruch auf Freistellung besteht nicht, wenn der Nutzer die Rechtsverletzung nicht zu vertreten hat.</li>
            <li class="has-line-data" data-line-start="54" data-line-end="55">Der Nutzer ist verpflichtet, Platypurse im Falle einer Inanspruchnahme durch Dritte auf Anforderung unverzüglich wahrheitsgemäß und vollständig alle Informationen zur Verteidigung zur Verfügung zu stellen, die für die Prüfung der Ansprüche und eine Verteidigung dagegen erforderlich sind.</li>
            <li class="has-line-data" data-line-start="55" data-line-end="57">Eine über diese Regelungen hinausgehende Haftung des Nutzers bleibt unberührt.</li>
        </ol>
        <h2 class="code-line" data-line-start=57 data-line-end=58 ><a id="9_Datenschutz_57"></a>9 Datenschutz</h2>
        <p class="has-line-data" data-line-start="58" data-line-end="59">Detaillierte Informationen zur Erhebung, Verarbeitung und Nutzung personenbezogener Daten des Nutzers im Zusammenhang mit der Registrierung, der Durchführung der Nutzungsvereinbarung und der Nutzung der Platypurse-Dienste finden sich in der <a href="./dataPrivacy">Datenschutzerklärung</a> von Platypurse.</p>
        <h2 class="code-line" data-line-start=60 data-line-end=61 ><a id="10_nderung_der_Nutzungsbedingungen_60"></a>10 Änderung der Nutzungsbedingungen</h2>
        <p class="has-line-data" data-line-start="61" data-line-end="62">Für Änderungen dieser Nutzungsbedingungen gilt: Der Nutzer kann den geänderten Nutzungsbedingungen einerseits zustimmen, indem er sie mit dem Einstellen einer Anzeige oder bei der Anfrage zu einem Inserat akzeptiert; Platypurse wird dies dann durch einen entsprechenden Hinweis besonders kennzeichnen. Andererseits kann Platypurse dem Nutzer jederzeit eine Änderung dieser Nutzungsbedingungen vorschlagen. Änderungen dieser Nutzungsbedingungen werden den Nutzern spätestens 30 Tage vor dem vorgeschlagenen Zeitpunkt ihres Wirksamwerdens in Textform (z. B. per E-Mail) angeboten. Die Zustimmung durch den Nutzer gilt als erteilt, wenn die Ablehnung nicht vor dem vorgeschlagenen Zeitpunkt des Wirksamwerdens der Änderungen gegenüber Platypurse in Textform angezeigt wird. Wenn der Nutzer mit den Änderungen nicht einverstanden ist, steht ihm bis zu dem vorgeschlagenen Zeitpunkt des Wirksamwerdens der Änderungen ein fristloses und kostenfreies Kündigungsrecht zu. Platypurse weist den Nutzer in der Nachricht, mit der die Änderungen angeboten werden, auch noch einmal besonders auf das Ablehnungsrecht, die Frist dafür und die Möglichkeit zur Kündigung hin. Die geänderten Nutzungsbedingungen werden zusätzlich auf der Website von Platypurse veröffentlicht.</p>
        <h2 class="code-line" data-line-start=63 data-line-end=64 ><a id="11_Schlussbestimmungen_63"></a>11 Schlussbestimmungen</h2>
        <ol>
            <li class="has-line-data" data-line-start="64" data-line-end="65">Auf die Nutzungsbedingungen, den Nutzungsvertrag und alle darauf basierende Vereinbarungen zwischen Platypurse und dem Nutzer findet ausschließlich das Recht der Bundesrepublik Deutschland Anwendung. Die Anwendung des UN-Kaufrechts (CISG) ist ausgeschlossen. Handelt der Nutzer als Verbraucher, sind darüber hinaus die zwingenden Verbraucherschutzbestimmungen anwendbar, die in dem Staat gelten, in dem der Nutzer seinen gewöhnlichen Aufenthalt hat, sofern diese dem Nutzer einen weitergehenden Schutz gewähren.</li>
            <li class="has-line-data" data-line-start="65" data-line-end="66">Ist der Nutzer Kaufmann im Sinne des Handelsgesetzbuchs, ein öffentlich-rechtliches Sondervermögen oder eine juristische Person des öffentlichen Rechts, ist Potsdam ausschließlicher Gerichtsstand für alle aus dem Nutzungsvertrag und den darauf basierenden Vereinbarungen entstehende Streitigkeiten. Gleiches gilt, wenn der Teilnehmer seinen Wohnsitz nach Vertragsschluss ins Ausland verlegt oder keinen allgemeinen Gerichtsstand in Deutschland hat. Für Nutzer, die Verbraucher sind, besteht ein Gerichtsstand am jeweiligen Wohnsitz des Nutzers. Für alle aus dem Nutzungsvertrag und diesen Nutzungsbedingungen entstehenden Streitigkeiten ist zusätzlicher Gerichtsstand für Verbraucher Potsdam.</li>
            <li class="has-line-data" data-line-start="66" data-line-end="67">Platypurse ist weder bereit noch verpflichtet, an Streitbeilegungsverfahren mit Verbrauchern vor einer Verbraucherschlichtungsstelle teilzunehmen (§ 36 Abs. 1 Nr. 1 VSBG).</li>
            <li class="has-line-data" data-line-start="67" data-line-end="68">Platypurse ist bereit, mit den hier aufgeführten Mediatoren zusammenzuarbeiten, um eine außergerichtliche Beilegung etwaiger Streitigkeiten mit gewerblichen Nutzern zu erzielen; vor Einleitung eines solchen Mediationsverfahrens sollten gewerbliche Nutzer jedoch versuchen, ihr Anliegen mit dem Kundenservice von Platypurse (siehe §1 Nr. 7 dieser Nutzungsbedingungen) zu klären.</li>
            <li class="has-line-data" data-line-start="68" data-line-end="69">Sollten einzelne Bestimmungen dieser Nutzungsbedingungen ganz oder teilweise nichtig oder unwirksam sein oder werden, so wird dadurch die Wirksamkeit der übrigen Bestimmungen nicht berührt. An die Stelle von nicht einbezogenen oder unwirksamen Bestimmungen dieser Nutzungsbedingungen tritt das Gesetzesrecht. Sofern solches Gesetzesrecht im jeweiligen Fall nicht zur Verfügung steht (Regelungslücke) oder zu einem untragbaren Ergebnis führen würde, werden die Parteien in Verhandlungen darüber eintreten, anstelle der nicht einbezogenen oder unwirksamen Bestimmung eine wirksame Regelung zu treffen, die ihr wirtschaftlich möglichst nahe kommt.</li>
        </ol>
    </div>
</main>